Update SDL 2 build configurations and dependencies
Updated package dependencies for various SDL 2 builds and modified paths for artifacts. Adjusted flags and build tools for iOS, Android, and Windows configurations.

diff --git a/.github/workflows/artifacts.yml b/.github/workflows/artifacts.yml
--- a/.github/workflows/artifacts.yml
+++ b/.github/workflows/artifacts.yml
@@ -10,29 +10,29 @@ jobs:
                 include:
                   - name: x86_64 SDL 2 (OGL)
                     flags: '-DNBC_PLATFORM=sdl2 -DNBC_GFX_API=OGL'
-                    packages: 'libsdl2-dev libopenal-dev'
+                    packages: 'libsdl2-dev libopenal-dev zlib1g-dev'
                     runner: ubuntu-24.04
                   - name: x86_64 SDL 2 (OGL + Shaders)
                     flags: '-DNBC_PLATFORM=sdl2 -DNBC_GFX_API=OGL_SHADERS'
-                    packages: 'libsdl2-dev libopenal-dev'
+                    packages: 'libsdl2-dev libopenal-dev zlib1g-dev'
                     runner: ubuntu-24.04
                   - name: i686 SDL 2 (OGL)
                     flags: '-DNBC_PLATFORM=sdl2 -DNBC_GFX_API=OGL -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32'
-                    packages: 'gcc-multilib g++-multilib libsdl2-dev:i386 libopenal-dev:i386'
+                    packages: 'gcc-multilib g++-multilib libsdl2-dev:i386 libopenal-dev:i386 zlib1g-dev:i386'
                     runner: ubuntu-22.04
                     i386: true
                   - name: i686 SDL 2 (OGL + Shaders)
                     flags: '-DNBC_PLATFORM=sdl2 -DNBC_GFX_API=OGL -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32'
-                    packages: 'gcc-multilib g++-multilib libsdl2-dev:i386 libopenal-dev:i386'
+                    packages: 'gcc-multilib g++-multilib libsdl2-dev:i386 libopenal-dev:i386 zlib1g-dev:i386'
                     runner: ubuntu-22.04
                     i386: true
                   - name: aarch64 SDL 2 (OGL)
                     flags: '-DNBC_PLATFORM=sdl2 -DNBC_GFX_API=OGL'
-                    packages: 'libsdl2-dev libopenal-dev'
+                    packages: 'libsdl2-dev libopenal-dev zlib1g-dev'
                     runner: ubuntu-24.04-arm
                   - name: aarch64 SDL 2 (OGL + Shaders)
                     flags: '-DNBC_PLATFORM=sdl2 -DNBC_GFX_API=OGL_SHADERS'
-                    packages: 'libsdl2-dev libopenal-dev'
+                    packages: 'libsdl2-dev libopenal-dev zlib1g-dev'
                     runner: ubuntu-24.04-arm
         name: Linux (${{ matrix.name }})
         runs-on: ${{ matrix.runner }}
@@ -82,70 +82,70 @@ jobs:
           - name: Pack cache
             run: cd ~ && tar cJf ccache.tar.xz .cache/ccache
 
-    flatpak:
-        strategy:
-            fail-fast: false
-            matrix:
-                include:
-                  - name: x86_64 SDL 2 (OGL)
-                    gfx-api: OGL
-                    arch: x86_64
-                    runner: ubuntu-24.04
-                  - name: x86_64 SDL 2 (OGL + Shaders)
-                    gfx-api: OGL_SHADERS
-                    arch: x86_64
-                    runner: ubuntu-24.04
-                  - name: aarch64 SDL 2 (OGL)
-                    gfx-api: OGL
-                    arch: aarch64
-                    runner: ubuntu-24.04-arm
-                  - name: aarch64 SDL 2 (OGL + Shaders)
-                    gfx-api: OGL_SHADERS
-                    arch: aarch64
-                    runner: ubuntu-24.04-arm
-        name: Flatpak (${{ matrix.name }})
-        runs-on: ${{ matrix.runner }}
-        steps:
-          - name: Get Time
-            id: get-time
-            run: echo "time=$(date -u '+%Y-%m-%d-%H:%M:%S')" >> $GITHUB_OUTPUT
-          - uses: actions/cache@v5
-            with:
-              path: ~/ccache.tar.xz
-              key: flatpak-artifact-${{ matrix.name }}-${{ steps.get-time.outputs.time }}
-              restore-keys: flatpak-artifact-${{ matrix.name }}-
-          - name: Unpack cache
-            run: cd ~ && [ -f ccache.tar.xz ] && tar xf ccache.tar.xz || true
-          - name: Checkout Repository
-            uses: actions/checkout@v6
-            with:
-                submodules: true
-          - name: Install Dependencies
-            run: |
-                sudo apt-get update
-                sudo apt-get install --no-install-recommends -y flatpak
-                flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
-                flatpak --user install -y \
-                    org.freedesktop.Platform/${{ matrix.arch }}/25.08 \
-                    org.freedesktop.Sdk/${{ matrix.arch }}/25.08
-          - name: Build
-            run: ./platforms/linux/build-flatpak.sh
-            env:
-              NOSTRIP: 1
-              ARCH: ${{ matrix.arch }}
-              NBC_GFX_API: ${{ matrix.gfx }}
-          - uses: actions/upload-artifact@v6
-            with:
-              name: Flatpak (${{ matrix.name }})
-              path: platforms/linux/build-flatpak/NBCraft-${{ matrix.arch }}.flatpak
-          - name: Pack cache
-            run: cd ~ && tar cJf ccache.tar.xz .cache/ccache
+    # flatpak:
+    #     strategy:
+    #         fail-fast: false
+    #         matrix:
+    #             include:
+    #               - name: x86_64 SDL 2 (OGL)
+    #                 gfx-api: OGL
+    #                 arch: x86_64
+    #                 runner: ubuntu-24.04
+    #               - name: x86_64 SDL 2 (OGL + Shaders)
+    #                 gfx-api: OGL_SHADERS
+    #                 arch: x86_64
+    #                 runner: ubuntu-24.04
+    #               - name: aarch64 SDL 2 (OGL)
+    #                 gfx-api: OGL
+    #                 arch: aarch64
+    #                 runner: ubuntu-24.04-arm
+    #               - name: aarch64 SDL 2 (OGL + Shaders)
+    #                 gfx-api: OGL_SHADERS
+    #                 arch: aarch64
+    #                 runner: ubuntu-24.04-arm
+    #     name: Flatpak (${{ matrix.name }})
+    #     runs-on: ${{ matrix.runner }}
+    #     steps:
+    #       - name: Get Time
+    #         id: get-time
+    #         run: echo "time=$(date -u '+%Y-%m-%d-%H:%M:%S')" >> $GITHUB_OUTPUT
+    #       - uses: actions/cache@v5
+    #         with:
+    #           path: ~/ccache.tar.xz
+    #           key: flatpak-artifact-${{ matrix.name }}-${{ steps.get-time.outputs.time }}
+    #           restore-keys: flatpak-artifact-${{ matrix.name }}-
+    #       - name: Unpack cache
+    #         run: cd ~ && [ -f ccache.tar.xz ] && tar xf ccache.tar.xz || true
+    #       - name: Checkout Repository
+    #         uses: actions/checkout@v6
+    #         with:
+    #             submodules: true
+    #       - name: Install Dependencies
+    #         run: |
+    #             sudo apt-get update
+    #             sudo apt-get install --no-install-recommends -y flatpak
+    #             flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
+    #             flatpak --user install -y \
+    #                 org.freedesktop.Platform/${{ matrix.arch }}/25.08 \
+    #                 org.freedesktop.Sdk/${{ matrix.arch }}/25.08
+    #       - name: Build
+    #         run: ./platforms/linux/build-flatpak.sh
+    #         env:
+    #           NOSTRIP: 1
+    #           ARCH: ${{ matrix.arch }}
+    #           NBC_GFX_API: ${{ matrix.gfx }}
+    #       - uses: actions/upload-artifact@v6
+    #         with:
+    #           name: Flatpak (${{ matrix.name }})
+    #           path: platforms/linux/build-flatpak/ReMCPE-${{ matrix.arch }}.flatpak
+    #       - name: Pack cache
+    #         run: cd ~ && tar cJf ccache.tar.xz .cache/ccache
 
     macos:
         strategy:
             fail-fast: false
         name: macOS
-        runs-on: macos-26
+        runs-on: macos-15
         steps:
           - name: Checkout Repository
             uses: actions/checkout@v6
@@ -178,18 +178,14 @@ jobs:
                   MPC="$(brew --prefix)" \
                   PATH="$PWD/cmake-4.2.3-macos-universal/CMake.app/Contents/bin:$PATH" \
                   ./platforms/macos/build.sh
-              tar cf workspacecache.tar platforms/macos/build/work/toolchain platforms/macos/build/work/toolchain-ppc platforms/macos/build/work/lastworkdir
+              tar cf workspacecache.tar platforms/macos/build/work/toolchain platforms/macos/build/work/toolchain-ppc
               mv workspacecache.tar ~
-              # workaround stupid upload-artifacts bs semantics
-              # if you point it at a folder the zip will have the contents of that folder instead of the folder itself
-              mkdir upload
-              mv platforms/macos/build/NBCraft.app upload
             env:
               NOSTRIP: 1
           - uses: actions/upload-artifact@v6
             with:
               name: macOS
-              path: upload
+              path: platforms/macos/build/ReMCPE
           - name: Pack cache
             run: cd ~ && tar cJf ccache.tar.xz Library/Caches/ccache workspacecache.tar
 
@@ -219,12 +215,12 @@ jobs:
           - name: Install Dependencies
             run: |
                 wget https://apt.llvm.org/llvm.sh
-                sudo bash llvm.sh 22
+                sudo bash llvm.sh 21
                 sudo apt-get update
                 sudo apt-get install --no-install-recommends -y \
                     cmake \
                     ccache \
-                    clang-22 \
+                    clang-21 \
                     libplist-utils \
                     libplist-dev \
                     libssl-dev
@@ -235,15 +231,15 @@ jobs:
               tar cf workspacecache.tar platforms/ios/build/work/toolchain
               mv workspacecache.tar ~
             env:
-              CLANG: clang-22
-              AR: llvm-ar-22
-              RANLIB: llvm-ranlib-22
-              LLVM_CONFIG: llvm-config-22
+              CLANG: clang-21
+              AR: llvm-ar-21
+              RANLIB: llvm-ranlib-21
+              LLVM_CONFIG: llvm-config-21
               NOSTRIP: 1
           - uses: actions/upload-artifact@v6
             with:
               name: iOS
-              path: platforms/ios/build/NBCraft.ipa
+              path: platforms/ios/build/ReMCPE.ipa
           - name: Pack cache
             run: cd ~ && tar cJf ccache.tar.xz .cache/ccache workspacecache.tar
 
@@ -251,13 +247,11 @@ jobs:
         strategy:
             fail-fast: false
             matrix:
-                include:
-                  - name: Native
-                    directory: platforms/android/project
-                    build_tools: 30.0.3
+                include: # TODO: switch to exclusively native android once it's fixed.
+                  # - name: Native
+                  #   directory: platforms/android/project
                   - name: SDL 2
                     directory: platforms/sdl/sdl2/android
-                    build_tools: 36.1.0
         name: Android (${{ matrix.name }})
         runs-on: ubuntu-24.04
         steps:
@@ -267,7 +261,7 @@ jobs:
           - uses: actions/cache@v5
             with:
               path: ~/ccache.tar.xz
-              key: android-artifact-${{ matrix.name }}-${{ steps.get-time.outputs.time }}
+              key: android-artifact-${{ steps.get-time.outputs.time }}
               restore-keys: android-artifact-
           - name: Unpack cache
             run: cd ~ && [ -f ccache.tar.xz ] && tar xf ccache.tar.xz || true
@@ -294,7 +288,7 @@ jobs:
             id: sign_apk
             env:
               ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
-              BUILD_TOOLS_VERSION: ${{ matrix.build_tools }}
+              BUILD_TOOLS_VERSION: 36.1.0
             if: ${{ env.ANDROID_KEYSTORE }}
             with:
               releaseDirectory: ${{ matrix.directory }}/app/build/outputs/apk/release
@@ -305,82 +299,76 @@ jobs:
             env:
               ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
             if: ${{ env.ANDROID_KEYSTORE }}
-            run: mv ${{ steps.sign_apk.outputs.signedReleaseFile }} NBCraft.apk
+            run: mv ${{ steps.sign_apk.outputs.signedReleaseFile }} ReMCPE.apk
           - name: Rename APK
             env:
               ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
             if: ${{ !env.ANDROID_KEYSTORE }}
-            run: mv ${{ matrix.directory }}/app/build/outputs/apk/release/app-release-unsigned.apk NBCraft.apk
+            run: mv ${{ matrix.directory }}/app/build/outputs/apk/release/app-release-unsigned.apk ReMCPE.apk
           - uses: actions/upload-artifact@v6
             with:
               name: Android (${{ matrix.name }})
-              path: NBCraft.apk
+              path: ReMCPE.apk
           - name: Pack cache
             run: cd ~ && tar cJf ccache.tar.xz .cache/ccache
 
-    windows:
+    mingw:
         strategy:
             fail-fast: false
             matrix:
                 include:
-                  - name: x86_64 (OGL)
-                    arch: x86_64
-                    gfx-api: OGL
-                  - name: x86_64 (OGL + Shaders)
-                    arch: x86_64
-                    gfx-api: OGL_SHADERS
-                  - name: i686 (OGL)
-                    arch: i686
-                    gfx-api: OGL
-                  - name: i686 (OGL + Shaders)
-                    arch: i686
-                    gfx-api: OGL_SHADERS
-        name: Windows (${{ matrix.name }})
+                  - name: Win32 (OGL)
+                    flags: '-DNBC_PLATFORM=windows -DNBC_GFX_API=OGL -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw-w64-toolchain.cmake'
+                  - name: Win32 (OGL + Shaders)
+                    flags: '-DNBC_PLATFORM=windows -DNBC_GFX_API=OGL_SHADERS -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw-w64-toolchain.cmake'
+                  - name: Win32 (OGL) 32-bit
+                    flags: '-DNBC_PLATFORM=windows -DNBC_GFX_API=OGL -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw-w64-toolchain-32bit.cmake'
+                  - name: Win32 (OGL + Shaders) 32-bit
+                    flags: '-DNBC_PLATFORM=windows -DNBC_GFX_API=OGL_SHADERS -DCMAKE_TOOLCHAIN_FILE=../cmake/mingw-w64-toolchain-32bit.cmake'
+        name: MinGW-w64 (${{ matrix.name }})
         runs-on: ubuntu-24.04
         steps:
-          - name: Checkout Repository
-            uses: actions/checkout@v6
-            with:
-                submodules: true
           - name: Get Time
             id: get-time
             run: echo "time=$(date -u '+%Y-%m-%d-%H:%M:%S')" >> $GITHUB_OUTPUT
           - uses: actions/cache@v5
             with:
               path: ~/ccache.tar.xz
-              key: windows-artifact-${{ matrix.name }}-${{ steps.get-time.outputs.time }}
-              restore-keys: windows-artifact-${{ matrix.name }}-
+              key: mingw-artifact-${{ matrix.name }}-${{ steps.get-time.outputs.time }}
+              restore-keys: mingw-artifact-${{ matrix.name }}-
           - name: Unpack cache
-            run: |
-              cd ~
-              [ -f ccache.tar.xz ] && tar xf ccache.tar.xz || true
-              [ -f workspacecache.tar ] && mv workspacecache.tar ${{ github.workspace }} || true
+            run: cd ~ && [ -f ccache.tar.xz ] && tar xf ccache.tar.xz || true
+          - name: Checkout Repository
+            uses: actions/checkout@v6
+            with:
+                submodules: true
           - name: Install Dependencies
             run: |
                 sudo apt-get update
                 sudo apt-get install --no-install-recommends -y \
                     build-essential \
-                    cmake \
+                    cmake ninja-build \
                     ccache \
-                    libgmp-dev \
-                    libmpfr-dev \
-                    libmpc-dev
+                    mingw-w64
           - name: Build
             run: |
-              [ -f workspacecache.tar ] && tar xf workspacecache.tar || true
-              ./platforms/windows/build.sh
-              tar cf workspacecache.tar platforms/windows/build/work/toolchain-${{ matrix.arch }}
-              mv workspacecache.tar ~
-            env:
-              ARCH: ${{ matrix.arch }}
-              NBC_GFX_API: ${{ matrix.gfx-api }}
-              NOSTRIP: 1
+                mkdir build
+                cd build
+                cmake .. -GNinja \
+                    -DCMAKE_BUILD_TYPE=Release \
+                    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
+                    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
+                    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
+                    ${{ matrix.flags }}
+                cmake --build .
           - uses: actions/upload-artifact@v6
             with:
               name: Windows (${{ matrix.name }})
-              path: platforms/windows/build/NBCraft
+              path: |
+                build/nbcraft.exe
+                build/assets
           - name: Pack cache
-            run: cd ~ && tar cJf ccache.tar.xz .cache/ccache workspacecache.tar
+            run: cd ~ && tar cJf ccache.tar.xz .cache/ccache
 
     switch:
         name: Nintendo Switch
